title: bri.ghten's dev note
lang: ko-KR
description: Just another jekyll theme
author: teahyuk

edit: false
logo: false
disqus: teahyuk

copyright: 
  revision: false

addons:
  - github
  - i18n
  - gems
  - analytics

theme: null # disable pages default theme

# use front matter sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - deps.sh
  - CODE_OF_CONDUCT.md
  - LICENSE
  - requirements.txt
  - jekyll-rtd-theme.gemspec
  - JekyllServe.sh
